export default defineAppConfig({
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/chat/index',
    'pages/home/index',
  ],
  window: {
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '创路 Agent',
    navigationBarTextStyle: 'black',
    backgroundColor: '#f3f4f6',
    backgroundTextStyle: 'dark',
  },
  usingComponents: {
    't-button': 'tdesign-miniprogram/button/button',
    't-icon': 'tdesign-miniprogram/icon/icon',
    't-input': 'tdesign-miniprogram/input/input',
    't-textarea': 'tdesign-miniprogram/textarea/textarea',
    't-avatar': 'tdesign-miniprogram/avatar/avatar',
    't-badge': 'tdesign-miniprogram/badge/badge',
    't-cell': 'tdesign-miniprogram/cell/cell',
    't-tag': 'tdesign-miniprogram/tag/tag',
    't-loading': 'tdesign-miniprogram/loading/loading',
    't-toast': 'tdesign-miniprogram/toast/toast',
    't-dialog': 'tdesign-miniprogram/dialog/dialog',
    't-popup': 'tdesign-miniprogram/popup/popup',
    't-empty': 'tdesign-miniprogram/empty/empty',
    't-steps': 'tdesign-miniprogram/steps/steps',
    't-step': 'tdesign-miniprogram/steps/step-item',
    't-navbar': 'tdesign-miniprogram/navbar/navbar',
    't-tabs': 'tdesign-miniprogram/tabs/tabs',
    't-image': 'tdesign-miniprogram/image/image',
    't-skeleton': 'tdesign-miniprogram/skeleton/skeleton',
    't-divider': 'tdesign-miniprogram/divider/divider',
    't-switch': 'tdesign-miniprogram/switch/switch',
    't-message': 'tdesign-miniprogram/message/message',
  },
});
